import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeClientSync from "@/components/ThemeClientSync";
import DiaryMobileMenu from "@/components/diary/DiaryMobileMenu";
// import AuthGuard from "@/components/login/AuthGuard"; // removed
// import { usePathname } from "next/navigation"; // not needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const PUBLIC_PATHS = ["/login", "/signup", "/forgot-password"]; // not needed

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body className="min-h-screen bg-gray-100 dark:bg-[#181925]">
        <ThemeClientSync />
        {children}
        <DiaryMobileMenu />
      </body>
    </html>
  );
}
