import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeClientSync from "@/components/ThemeClientSync";
import DiaryMobileMenu from "@/components/diary/DiaryMobileMenu";
import AuthGuard from "@/components/login/AuthGuard";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PUBLIC_PATHS = ["/login", "/signup", "/forgot-password"];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // You can't use usePathname() directly in the root layout (server component),
  // so use client-side check inside AuthGuard/DiaryMobileMenu.
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <body className="min-h-screen bg-gray-100 dark:bg-[#181925]">
        <ThemeClientSync />
        {/* AuthGuard protects everything except /login, /signup, /forgot-password */}
        <AuthGuard>
          {children}
          {/* DiaryMobileMenu hides itself automatically on login/signup/etc */}
          <DiaryMobileMenu />
        </AuthGuard>
      </body>
    </html>
  );
}
